# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Hinterface.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10Hinterface.proto\x12\x05hello\"$\n\x11helloWorldRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"$\n\x12helloWorldResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32L\n\x05Hello\x12\x43\n\nhelloWorld\x12\x18.hello.helloWorldRequest\x1a\x19.hello.helloWorldResponse\"\x00\x62\x06proto3')



_HELLOWORLDREQUEST = DESCRIPTOR.message_types_by_name['helloWorldRequest']
_HELLOWORLDRESPONSE = DESCRIPTOR.message_types_by_name['helloWorldResponse']
helloWorldRequest = _reflection.GeneratedProtocolMessageType('helloWorldRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOWORLDREQUEST,
  '__module__' : 'Hinterface_pb2'
  # @@protoc_insertion_point(class_scope:hello.helloWorldRequest)
  })
_sym_db.RegisterMessage(helloWorldRequest)

helloWorldResponse = _reflection.GeneratedProtocolMessageType('helloWorldResponse', (_message.Message,), {
  'DESCRIPTOR' : _HELLOWORLDRESPONSE,
  '__module__' : 'Hinterface_pb2'
  # @@protoc_insertion_point(class_scope:hello.helloWorldResponse)
  })
_sym_db.RegisterMessage(helloWorldResponse)

_HELLO = DESCRIPTOR.services_by_name['Hello']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOWORLDREQUEST._serialized_start=27
  _HELLOWORLDREQUEST._serialized_end=63
  _HELLOWORLDRESPONSE._serialized_start=65
  _HELLOWORLDRESPONSE._serialized_end=101
  _HELLO._serialized_start=103
  _HELLO._serialized_end=179
# @@protoc_insertion_point(module_scope)
